In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([1,2,5,7,3,8])
print(s1)

0    1
1    2
2    5
3    7
4    3
5    8
dtype: int64

In [3]:
s1 = pd.Series([1,2,5,7,3,8],index= ["noumna","ali","javed","mudsir","abkar","khan"])
print(s1)
print(s1.shape,s1.dtype)
# s2 = pd.Series([6,2,7,2,8,2],index= ["noumna1","ali2","javed3","mudsir4","abkar5","khan6"])
# print(s1+s2)
print(s1["ali"])
# print(s1[0])
s1["ali"] = 44
print(s1)

noumna    1
ali       2
javed     5
mudsir    7
abkar     3
khan      8
dtype: int64
(6,) int64
2
noumna     1
ali       44
javed      5
mudsir     7
abkar      3
khan       8
dtype: int64

In [4]:
# creating Dataframs from dictionary 
info = {
    "name" : ["ali", "javed", "khan"],
    "age" : [13,62,73],
    "salary" : [667,773,884]
}
d1 = pd.DataFrame(info)
print(d1)
print(d1.index,d1.columns)

# creating from list of lists
d2 = pd.DataFrame([ ["nouman",36], ["ali",26], ["khan", 74] ] , columns = ["Name","Age"], index = ["mirali","taxila","punjab"] )
print(d2)

# creating from NumPy arrays
import numpy as np
arr = np.array([[1,2,3], [4,5,6] ])
d3 = pd.DataFrame(arr, columns = ["A","B","C"])
print(d3)

    name  age  salary
0    ali   13     667
1  javed   62     773
2   khan   73     884
RangeIndex(start=0, stop=3, step=1) Index(['name', 'age', 'salary'], dtype='object')
          Name  Age
mirali  nouman   36
taxila     ali   26
punjab    khan   74
   A  B  C
0  1  2  3
1  4  5  6

In [5]:
# loading data
df = pd.read_csv("raw_data.csv")
print(df)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [6]:
df = pd.read_csv("globalAirQuality.csv")
# print(df)
print(df.shape)
# print(df.nunique())
# df.head()
df.tail()
df.describe()

(18000, 15)

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [7]:
df["city"]
df[["city", "aqi"]]
df["city"]
df.loc[0:3]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956

In [8]:
# columns
df[["city","aqi"] ]

# rows 
df.loc[0] 
df.loc[0:4] # inclucice 


df.loc[0, "city"]
# df.iloc[0, "city"] # this will throw error
df.iloc[0:3, 2:5]

# cells
df.iat[0,0]
df.at[0,"city"]

'New York'

In [9]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [10]:
# filtering data
a=df[ df["temperature"] >35 ] ["city"]
a.loc[6]

# Query
df.query("temperature	> 35")["city"]
df.query('temperature	> 20  & city == "New York" ')["so2"]

2      9.538
3      7.609
6      7.641
7      6.945
8      6.779
       ...
354    1.458
355    9.098
356    6.786
358    9.725
359    7.350
Name: so2, Length: 195, dtype: float64

In [11]:
df = pd.read_csv("raw_data.csv")
df.isnull().sum()
df.dropna()
df.dropna(axis = 1)
df.fillna(0)
clean_data = df
mean = clean_data["age"].mean()
clean_data["age"] = clean_data["age"].fillna(mean)
clean_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [12]:
df.duplicated()
df.drop_duplicates(inplace = True)
df.dtypes
df2 = df["age"].astype("int64").copy()
df2

0     29
2     32
3     32
4     34
5     27
6     45
7     38
8     29
9     32
10    31
Name: age, dtype: int64

In [14]:
# df.loc[0, "country"] 
df.iloc[0, "country"]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types