In [3]:
import requests

In [23]:
URL  = "https://stephen-king-api.onrender.com/api/books"
URL1  = "https://api.alquran.cloud/v1/ayah/random"
url2 = "https://api.alquran.cloud/v1/documentation/openapi/yaml"
res0= requests.get(URL)
res1= requests.get(URL1)
res2= requests.get(url2)

In [42]:
data_0 = res0.json()
# print(data_0)

import pandas as pd
df0 = pd.json_normalize(data_0["data"])
df0

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]
63,72,1979,The Roopak Zone,the-roopak-zone,Viking Press,978-0-670-26069697-5,428,"[Runner-up (2nd place), Locus Award for Best F...",2026-06-26T18:20:32.285Z,[]

In [40]:
data_1 = res1.json()
# data_2 = res2.json()
data_1

{'code': 200,
 'status': 'OK',
 'data': {'number': 4939,
  'text': 'فَبِأَیِّ ءَالَاۤءِ رَبِّكُمَا تُكَذِّبَانِ\n',
  'edition': {'identifier': 'quran-uthmani-quran-academy',
   'language': 'ar',
   'name': 'القرآن الكريم برسم العثماني (quran-academy)',
   'englishName': 'Modified Quran Uthmani Text from the Quran Academy to work with the Kitab font',
   'format': 'text',
   'type': 'quran',
   'direction': 'rtl'},
  'surah': {'number': 55,
   'name': 'سُورَةُ الرَّحۡمَٰن',
   'englishName': 'Ar-Rahmaan',
   'englishNameTranslation': 'The Beneficent',
   'numberOfAyahs': 78,
   'revelationType': 'Medinan'},
  'numberInSurah': 38,
  'juz': 27,
  'manzil': 7,
  'page': 532,
  'ruku': 467,
  'hizbQuarter': 213,
  'sajda': False}}

In [44]:
df1 = pd.json_normalize(data_1)
df1

,code,status,data.number,data.text,data.edition.identifier,data.edition.language,data.edition.name,data.edition.englishName,data.edition.format,data.edition.type,...,data.surah.englishNameTranslation,data.surah.numberOfAyahs,data.surah.revelationType,data.numberInSurah,data.juz,data.manzil,data.page,data.ruku,data.hizbQuarter,data.sajda
0,200,OK,4939,فَبِأَیِّ ءَالَاۤءِ رَبِّكُمَا تُكَذِّبَانِ\n,quran-uthmani-quran-academy,ar,القرآن الكريم برسم العثماني (quran-academy),Modified Quran Uthmani Text from the Quran Aca...,text,quran,...,The Beneficent,78,Medinan,38,27,7,532,467,213,False

In [57]:
url3 = "https://dogapi.dog/api/v2/breeds"
res3 = requests.get(url3)

In [58]:
res3
print(res3.headers["Content-Type"])

application/vnd.api+json; charset=utf-8

In [60]:
print(res3.url)
print(res3.text[:300])

https://dogapi.dog/api/v2/breeds
{"data":[{"id":"036feed0-da8a-42c9-ab9a-57449b530b13","type":"breed","attributes":{"name":"Affenpinscher","description":"The Affenpinscher is a small and playful breed of dog that was originally bred in Germany for hunting small game. They are intelligent, energetic, and affectionate, and make excel

In [64]:
data3= res3.json()
data3
df3 = pd.json_normalize(data3["data"])
df3

,id,type,attributes.name,attributes.description,attributes.life.max,attributes.life.min,attributes.male_weight.max,attributes.male_weight.min,attributes.female_weight.max,attributes.female_weight.min,attributes.hypoallergenic,relationships.group.data.id,relationships.group.data.type
0,036feed0-da8a-42c9-ab9a-57449b530b13,breed,Affenpinscher,The Affenpinscher is a small and playful breed...,16,14,5,3,5,3,True,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group
1,dd9362cc-52e0-462d-b856-fccdcf24b140,breed,Afghan Hound,The Afghan Hound is a large and elegant breed ...,14,12,27,23,25,20,False,be0147df-7755-4228-b132-2518c0c6d10d,group
2,1460844f-841c-4de8-b788-271aa4d63224,breed,Airedale Terrier,The Airedale Terrier is a large and powerful b...,14,12,23,20,20,18,False,1bbf373b-1937-4e73-9863-45385daa4979,group
3,e7e99424-d514-4b56-9f0c-05736f6dd22d,breed,Akita,"The Akita is a large, muscular dog breed that ...",12,10,60,35,50,35,False,56081cf0-fdf2-4114-9bf7-23a3f5b6af91,group
4,667c7359-a739-4f2b-abb4-98867671e375,breed,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...,15,12,7,6,7,6,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,095a1856-6506-478d-a7a8-206847d5e702,breed,Wirehaired Vizsla,The Wirehaired Vizsla is a medium-sized breed ...,15,12,30,25,30,25,False,ab110192-e41b-43ff-a630-f7aee156b33a,group
279,c6b12b96-9f53-445b-8f3e-bf867c761dca,breed,Working Kelpie,The Working Kelpie is a medium-sized breed of ...,15,12,20,16,20,16,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
280,43cdadb4-851b-4a3a-99c1-5f63d08d97f8,breed,Xoloitzcuintli,"The Xoloitzcuintli, also known as the Mexican ...",15,12,15,10,15,10,True,7f6ea988-366a-4e20-b4ba-4d04274fea61,group
281,052684bc-a484-4f29-b953-d5ccf6a3d5e6,breed,Yakutian Laika,The Yakutian Laika is a medium-sized breed of ...,15,12,30,18,30,18,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
282,ce40589c-295a-4259-9e83-711854db8129,breed,Yorkshire Terrier,"The Yorkshire Terrier is a small, intelligent ...",15,12,3,2,3,2,False,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group

In [79]:
try:
    url_s = "https://books.toscrape.com/"
    res4 = requests.get(url_s,timeout=5)
    res4.raise_for_status()
except requests.exceptions.RequestException as e:
    print("Error: ", e)

In [80]:
print(res4.headers["Content-Type"])
# if res4.status_code == 200:
#     print(res4.text)
# print(res.content)  
print(res4.headers)

text/html
{'Date': 'Mon, 20 Jul 2026 09:16:08 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Last-Modified': 'Wed, 08 Feb 2023 21:02:32 GMT', 'ETag': 'W/"63e40de8-c85e"', 'Strict-Transport-Security': 'max-age=0; includeSubDomains; preload', 'Content-Encoding': 'br'}

In [81]:
with open("scraped_data/data_1.html","w") as f:
    f.write(res4.text)

In [84]:
from bs4 import BeautifulSoup

In [85]:
with open("scraped_data/data_1.html","r") as f:
    html_content = f.read()

In [86]:
soup = BeautifulSoup(html_content,"lxml")

In [106]:
all_h3 = soup.find_all("h3")
# for h3 in all_h3:
#     h3.get_text()

In [116]:
b_list = []

for h3 in all_h3:
    # Get the current book's article
    article = h3.find_parent("article", class_="product_pod")

    # Full book title
    book_name = h3.find("a")["title"]

    # Book price
    price = article.find("p", class_="price_color").get_text(strip=True)

    # Availability
    availability = article.find("p", class_="instock availability").get_text(strip=True)

    # Rating
    rating = article.find("p", class_="star-rating")["class"][1]
    b_dict = {
        "book name": book_name,
        "book price": price,
        "availability": availability,
        "rating": rating
    }
    b_list.append(b_dict)
    print(f"Book Name   : {book_name}")
    print(f"Price       : {price}")
    print(f"Availability: {availability}")
    print(f"Rating      : {rating}")
    print("-" * 50)

Book Name   : A Light in the Attic
Price       : Â£51.77
Availability: In stock
Rating      : Three
--------------------------------------------------
Book Name   : Tipping the Velvet
Price       : Â£53.74
Availability: In stock
Rating      : One
--------------------------------------------------
Book Name   : Soumission
Price       : Â£50.10
Availability: In stock
Rating      : One
--------------------------------------------------
Book Name   : Sharp Objects
Price       : Â£47.82
Availability: In stock
Rating      : Four
--------------------------------------------------
Book Name   : Sapiens: A Brief History of Humankind
Price       : Â£54.23
Availability: In stock
Rating      : Five
--------------------------------------------------
Book Name   : The Requiem Red
Price       : Â£22.65
Availability: In stock
Rating      : One
--------------------------------------------------
Book Name   : The Dirty Little Secrets of Getting Your Dream Job
Price       : Â£33.34
Availability: In stock
Rating      : Four
--------------------------------------------------
Book Name   : The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Price       : Â£17.93
Availability: In stock
Rating      : Three
--------------------------------------------------
Book Name   : The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Price       : Â£22.60
Availability: In stock
Rating      : Four
--------------------------------------------------
Book Name   : The Black Maria
Price       : Â£52.15
Availability: In stock
Rating      : One
--------------------------------------------------
Book Name   : Starving Hearts (Triangular Trade Trilogy, #1)
Price       : Â£13.99
Availability: In stock
Rating      : Two
--------------------------------------------------
Book Name   : Shakespeare's Sonnets
Price       : Â£20.66
Availability: In stock
Rating      : Four
--------------------------------------------------
Book Name   : Set Me Free
Price       : Â£17.46
Availability: In stock
Rating      : Five
--------------------------------------------------
Book Name   : Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Price       : Â£52.29
Availability: In stock
Rating      : Five
--------------------------------------------------
Book Name   : Rip it Up and Start Again
Price       : Â£35.02
Availability: In stock
Rating      : Five
--------------------------------------------------
Book Name   : Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Price       : Â£57.25
Availability: In stock
Rating      : Three
--------------------------------------------------
Book Name   : Olio
Price       : Â£23.88
Availability: In stock
Rating      : One
--------------------------------------------------
Book Name   : Mesaerion: The Best Science Fiction Stories 1800-1849
Price       : Â£37.59
Availability: In stock
Rating      : One
--------------------------------------------------
Book Name   : Libertarianism for Beginners
Price       : Â£51.33
Availability: In stock
Rating      : Two
--------------------------------------------------
Book Name   : It's Only the Himalayas
Price       : Â£45.17
Availability: In stock
Rating      : Two
--------------------------------------------------

In [117]:
for i in b_list:
    print(i)

{'book name': 'A Light in the Attic', 'book price': 'Â£51.77', 'availability': 'In stock', 'rating': 'Three'}
{'book name': 'Tipping the Velvet', 'book price': 'Â£53.74', 'availability': 'In stock', 'rating': 'One'}
{'book name': 'Soumission', 'book price': 'Â£50.10', 'availability': 'In stock', 'rating': 'One'}
{'book name': 'Sharp Objects', 'book price': 'Â£47.82', 'availability': 'In stock', 'rating': 'Four'}
{'book name': 'Sapiens: A Brief History of Humankind', 'book price': 'Â£54.23', 'availability': 'In stock', 'rating': 'Five'}
{'book name': 'The Requiem Red', 'book price': 'Â£22.65', 'availability': 'In stock', 'rating': 'One'}
{'book name': 'The Dirty Little Secrets of Getting Your Dream Job', 'book price': 'Â£33.34', 'availability': 'In stock', 'rating': 'Four'}
{'book name': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'book price': 'Â£17.93', 'availability': 'In stock', 'rating': 'Three'}
{'book name': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'book price': 'Â£22.60', 'availability': 'In stock', 'rating': 'Four'}
{'book name': 'The Black Maria', 'book price': 'Â£52.15', 'availability': 'In stock', 'rating': 'One'}
{'book name': 'Starving Hearts (Triangular Trade Trilogy, #1)', 'book price': 'Â£13.99', 'availability': 'In stock', 'rating': 'Two'}
{'book name': "Shakespeare's Sonnets", 'book price': 'Â£20.66', 'availability': 'In stock', 'rating': 'Four'}
{'book name': 'Set Me Free', 'book price': 'Â£17.46', 'availability': 'In stock', 'rating': 'Five'}
{'book name': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'book price': 'Â£52.29', 'availability': 'In stock', 'rating': 'Five'}
{'book name': 'Rip it Up and Start Again', 'book price': 'Â£35.02', 'availability': 'In stock', 'rating': 'Five'}
{'book name': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'book price': 'Â£57.25', 'availability': 'In stock', 'rating': 'Three'}
{'book name': 'Olio', 'book price': 'Â£23.88', 'availability': 'In stock', 'rating': 'One'}
{'book name': 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'book price': 'Â£37.59', 'availability': 'In stock', 'rating': 'One'}
{'book name': 'Libertarianism for Beginners', 'book price': 'Â£51.33', 'availability': 'In stock', 'rating': 'Two'}
{'book name': "It's Only the Himalayas", 'book price': 'Â£45.17', 'availability': 'In stock', 'rating': 'Two'}

In [112]:
books_list= []

for h3 in all_h3:
    # print(h3.get_text())
    print(h3.find_next("p","instock availability"))
    # print(h3.find_previous("p"))
# for i in book_names:
#     print(i)

<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>